### ISSUE TITLE
Allow to add metamethods from Lua

### ISSUE THREAD

**Issue by dtroitskiy** [kunitoki/LuaBridge3#131]
It would be nice to be able to add metamethods for bound classes from Lua scripts.
For example, to add or override existing `__tostring` or `__eq` metamethods.
From C++ you can do this no problem:
```
.addFunction(
  "__tostring",
  function<string(Test*)>(
  [](Test* p)
  {
    return format("Test({})", p->getName());
  }))
```
But from Lua I tried these two methods (I added `visibleMetatables` option to bound class):
```
local mt = getmetatable(Test)
mt.__tostring = function(self)
   return ('Test(%s)'):format(self.name)
end
setmetatable(Test, mt)
```
and
```
function Test:__tostring()
  return ('Test(%s)'):format(self.name)
end
```
and none of these works.
Although I figured out second variant is probably the correct way, because I assume `Test` already plays the role of metatable in this context, and also this wouldn't work until I also add `extensibleClass | allowOverridingMethods` options to bound class, saying `immutable member '__tostring'` otherwise.
But still, even with these options added, metamethod doesn't work.

**Comment by kunitoki** [comment]
Adding metamethods from lua over luabridge exposed classes can be problematic, mostly because of how luabridge manages metatables for those classes internally. If you need to be able to overwrite these methods, i suggest you create a pure lua class and compose on it c++ binded classes instead of going overboard with trying to "patch" c++ exposed classes.

**Comment by kunitoki** [comment]
Would be nice if you could test it

**Comment by dtroitskiy** [comment]
Yep, `__tostring` works now. But unfortunately `__eq` doesn't, I didn't test the other metamethods, but I suppose they may not work too.
I assume `__eq` should work like this:
```
function Test:__eq(other)
  return self.name == other.name
end
```
or this, doesn't really matter:
```
function Test.__eq(a, b)
  return a.name == b.name
end
```

**Comment by kunitoki** [comment]
That is strange, i don't understand how would metamethods be treated differently

**Comment by dtroitskiy** [comment]
Yeah, I also wasn't sure if that's possible, but I'm not aware of implementation LuaBridge details, so I supposed maybe there's some edge case with `__tostring`.
Also there is a chance I did something wrong in my testing, so would be nice if you test too.
But I double checked how `__eq` operator is written, so there shouldn't be an error.

**Comment by kunitoki** [comment]
There was an issue in the way new index metamethod was behaving with registered metamethods vs non registered ones. Because luabridge provided __tostring, the resolution was working while other metamethods (which were not already registered in the metatable) were not resolvable. Should be fixed, but will try to create more unit tests.

**Comment by dtroitskiy** [comment]
Sorry for delay with reply.
Yes, now looks like everything works as expected, I tested `__eq` and `__add`.
Thank you for your efforts!
