### ISSUE TITLE
Can't add function in table 

### ISSUE THREAD

**Issue by IXDH** [kunitoki/LuaBridge3#16]
When i try add function in table, give me null error ('C:\scripts\Example.lua:11:' and no more)

```
getGlobalNamespace(L)
.beginNamespace("Entities")
	.addFunction("GetLocalHero", [&]() { 
		auto table = luabridge::newTable(L);
		table["index"] = 150;
		table["Health"] = [&]() {
		return 500;
		};
		return table;
	})
.endNamespace();
```

When i delete table["health"], everything is okay, but when i try to bind function in table, something is wrong

in lua:
cout(tostring(Entities.GetLocalHero().Health()))

lua version 5.4.2, luabridge: "LuaBridge3-master.zip"

**Comment by kunitoki** [comment]
That will not work, luabridge assumes methods are registered via the namespace infrastructure, so you need to do something like:
```
    luabridge::getGlobalNamespace(L)
        .beginNamespace("Entities")
        .addFunction("GetLocalHero", [&]() {
            auto table = luabridge::newTable(L);
            table.push(L);
            
            luabridge::getNamespaceFromStack(L)
                .addProperty("index", +[] { return 150; })
                .addFunction("Health", [&] { return 500; });

            table.pop();
            return table;
        })
    .endNamespace();
```

But this is not an optional way to go, i would suggest you register a class for your Hero (assigning properties and methods there) and return instances of that class from `GetLocalHero` instead of returning tables.

**Comment by IXDH** [comment]
ty very much
